### ISSUE TITLE
Testing a local Kibana with elastasks 

### ISSUE THREAD

**Issue by lizozom** [jzzfs/elastasks#2]
I'm trying to test the tool you developed, following https://github.com/elastic/kibana/issues/44193#issuecomment-696033109
Whether I run it locally or from `https://elastasks.vercel.app`, I get a CORS error trying to access my localhost Kibana

```
Access to XMLHttpRequest at 'http://localhost:5620/' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Any suggestions?

**Comment by jzzfs** [comment]
Have you set up your `http.cors*` config properly? It's in `elasticsearch.yml`. More info [here](https://stackoverflow.com/a/37418737/8160318).
